"use strict";
const assert=require("node:assert/strict"),Game=require("./override");
const game=new Game({physical:false});
assert(game.robots.every(r=>game.touchesPerimeter(r)));
assert.equal(game.touchesPerimeter({x:59,y:0,theta:45,width:18,length:18}),true);
assert.equal(game.touchesPerimeter({x:59,y:0,theta:0,width:18,length:18}),false);
assert.equal(game.setRobotSize('red-1',{width:0}).ok,false);
assert.equal(game.pins.length,63);assert.equal(game.cups.length,56);
assert.equal(game.goals.filter(g=>g.alliance==="red").length,2);
assert.equal(game.goals.filter(g=>g.alliance==="blue").length,2);
assert.equal(game.goals.filter(g=>!g.alliance).length,5);
assert(game.cups.every(c=>c.halves.includes("transparent")&&c.halves.includes("opaque")));
assert.equal(game.pins.filter(p=>p.placed).length,5);
const fieldRed=()=>game.pins.find(p=>p.halves.includes("red")&&p.location==="field"&&!p.placed);
const red=fieldRed();assert(game.placePin(red.id,"g-red-sw",{visibleHalf:"red"}).ok);
assert.equal(game.scorePins().red,5);
assert.equal(game.placePin(red.id,"g-blue-ne",{replace:true}).ok,false);
const bad=fieldRed();assert.equal(game.placePin(bad.id,"g-red-s",{visibleHalves:["red","red"]}).ok,false);
assert.equal(bad.placed,false);
assert.equal(game.placePin(bad.id,"g-red-sw").ok,false,"Cannot stack two pins without a cup");
assert.equal(game.setPossession("red-1",{pinId:"invented"}).ok,false);
assert.equal(game.setPossession("blue-1",{pinId:game.robots[0].possession.pinId}).ok,false);
game.startMatch();for(let i=0;i<15;i++)game.tick(1);
assert.deepEqual(game.autonomousBonus,{red:12,blue:0});
assert.deepEqual(game.autonomousScores,{red:5,blue:0});
const blue=game.pins.find(p=>p.halves.includes("blue")&&p.location==="field");
assert(game.placePin(blue.id,"g-blue-ne",{visibleHalf:"blue"}).ok);
game.setToggle("toggle-north","blue");
for(let i=0;i<105;i++)game.tick(1);
assert.deepEqual(game.autonomousBonus,{red:12,blue:0},"Driver actions cannot rewrite autonomous bonus");
const final=game.score();game.setRobotPose("blue-1",{x:0,y:0});assert.deepEqual(game.score(),final);
const midfield=new Game({physical:false}),cup=midfield.cups[0];
assert(midfield.placeCup(cup.id,"g-neutral-tall").ok);
const mixed=midfield.pins.find(p=>p.halves.includes("red")&&p.location==="field");
assert(midfield.placePin(mixed.id,"g-neutral-tall",{visibleHalves:["red","yellow"]}).ok);
midfield.setRobotPose("red-1",{x:0,y:0});
assert.equal(midfield.scorePins(false).red,5,"Auto excludes midfield yellow ownership, not colored halves");
assert(midfield.scorePins(true).red>5);
assert.equal(midfield.isInMidfield({x:30,y:30,theta:0,width:2,length:2}),false);
assert.equal(midfield.isInMidfield({x:23,y:0,theta:0,width:2,length:2}),true);
const g=new Game({physical:false});g.startMatch();g.setRobotPose("red-1",{x:-64,y:60});
assert.equal(g.interact("red-1","load","cup").ok,false);
for(let i=0;i<15;i++)g.tick(1);
assert(g.interact("red-1","load","cup").ok);
assert(g.interact("red-1","pickup","cup").ok);
assert.equal(g.interact("red-1","pickup","cup").ok,false);
const held=g.cup(g.robots[0].possession.cupId),before=held.up;
assert(g.interact("red-1","flip","cup").ok);assert.notEqual(held.up,before);
assert(g.interact("red-1","drop","cup").ok);assert.equal(held.status,"field");
console.log("PASS: Override inventory, stack validity, visibility, autonomous snapshot, final freeze, diamond contact, possession and match loads.");
