/*
 * Copyright (c) 2026 Pedro Pathing
 * SPDX-License-Identifier: BSD-3-Clause
 */
package com.pedropathing.paths.curves.bezier;

import static com.pedropathing.utils.Utils.clamp;

import com.pedropathing.math.Matrix;
import com.pedropathing.math.Pose;
import com.pedropathing.math.Vector;
import com.pedropathing.math.Vector2D;
import com.pedropathing.paths.TValue;
import com.pedropathing.paths.curves.Curve;
import com.pedropathing.utils.BijectiveMap;
import com.pedropathing.utils.Utils;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

/**
 * This is the BezierCurve class. This class handles the creation of Bezier curves, which are used
 * as the basis of the path for the Path class. Bezier curves are parametric curves defined by a set
 * of control points. So, they take in one input, t, that ranges from [0, 1] and that returns a point
 * on the curve. Essentially, Bezier curves are a way of defining a parametric line easily. You can
 * read more on Bezier curves here: <a href="https://en.wikipedia.org/wiki/Bézier_curve">...</a>
 *
 * @author Havish Sripada - 12808 Revamped Robotics
 * @author Anyi Lin - 10158 Scott's Bots
 * @author Aaron Yang - 10158 Scott's Bots
 * @author Harrison Womack - 10158 Scott's Bots
 * @author William Phomphakdee - 7462 Not to Scale Alumni
 * @version 2.0, 08/28/2026
 */
public class BezierCurve implements Curve {
    private static final double SUBDIVISION_TOLERANCE = 1e-5;
    private static final int MAX_SUBDIVISION_DEPTH = 15;

    private ArrayList<Vector2D> controlPoints;
    protected final int SEARCH_LIMIT = 10;
    private double length;
    private Matrix cachedMatrix;
    private PolynomialMatrix tMatrix;
    protected BijectiveMap completionMap = new BijectiveMap();

    /**
     * This is the default constructor for the BezierCurve class. It initializes an empty BezierCurve.
     * This is not recommended to use, as it does not set any control points or path constraints.
     */
    public BezierCurve() {}

    /**
     * This constructor creates a BezierCurve with the specified control points and path constraints.
     * @param controlPoints the control points for the BezierCurve, which must be at least 3 points.
     */
    public BezierCurve(List<Vector2D> controlPoints) {
        if (controlPoints.size() < 3) {
            throw new IllegalArgumentException("Too few control points");
        }

        this.controlPoints = new ArrayList<>(controlPoints);
        initialize();
    }

    /**
     * This constructor creates a BezierCurve with the specified control points and path constraints.
     * @param controlPoints the control points for the BezierCurve, which must be at least 3 points.
     */
    public BezierCurve(Pose... controlPoints) {
        this(Arrays.stream(controlPoints).map(Pose::toVector2D).collect(Collectors.toCollection(ArrayList::new)));
    }

    /**
     * This constructor creates a BezierCurve with the specified control points and path constraints.
     * @param controlPoints the control points for the BezierCurve, which must be at least 3 points.
     */
    public BezierCurve(Vector2D... controlPoints) {
        this(new ArrayList<>(Arrays.asList(controlPoints)));
    }

    /**
     * This handles most of the initialization of the BezierCurve that is called from the constructor.
     */
    private void initialize() {
        generateBezierCurve();
        approximateLength();
        length = completionMap.get(1.0);
    }

    /**
     * This generates the Bezier curve. It assumes that the ArrayList of control points has been set.
     * This caches the matrix generated by multiplying the characteristic matrix and the matrix where each control
     * point is a row vector.
     */
    private void generateBezierCurve() {

        double[][] controlPointMatrix = new double[this.controlPoints.size()][2];
        for (int i = 0; i < this.controlPoints.size(); i++) {
            Vector2D p = controlPoints.get(i);
            controlPointMatrix[i] = new double[] {p.x(), p.y()};
        }
        Matrix controlMatrix = new Matrix(controlPointMatrix);
        this.cachedMatrix = BasisMatrixSupplier.getBezierCharacteristicMatrix(this.controlPoints.size())
                .times(controlMatrix);

        this.tMatrix = new PolynomialMatrix(this.controlPoints.size());
    }

    /**
     * This approximates the length of the BezierCurve using adaptive subdivision.
     * It recursively splits the curve where curvature is high to build an accurate completionMap.
     *
     * @return returns the approximated length of the BezierCurve.
     */
    private void approximateLength() {
        completionMap.put(0.0, 0.0);
        Vector2D p0 = get(0.0);
        Vector2D p1 = get(1.0);
        subdivide(0.0, 1.0, p0, p1, 0);
    }

    private void subdivide(double startT, double endT, Vector2D startPoint, Vector2D endPoint, int depth) {
        double tMid = (startT + endT) / 2.0;
        Vector2D pMid = get(tMid);
        double length = startPoint.distance(endPoint);
        double splitLength = startPoint.distance(pMid) + pMid.distance(endPoint);

        if (Math.abs(splitLength - length) < SUBDIVISION_TOLERANCE || depth >= MAX_SUBDIVISION_DEPTH) {
            double currentLength = completionMap.get(startT) + splitLength;
            completionMap.put(tMid, completionMap.get(startT) + startPoint.distance(pMid));
            completionMap.put(endT, currentLength);
            return;
        }

        subdivide(startT, tMid, startPoint, pMid, depth + 1);
        subdivide(tMid, endT, pMid, endPoint, depth + 1);
    }

    /**
     * This returns the point on the Bezier curve that is specified by the parametric t value. A
     * Bezier curve is a parametric function that returns points along it with t ranging from [0, 1],
     * with 0 being the beginning of the curve and 1 being at the end. The Follower will follow
     * BezierCurves from 0 to 1, in terms of t.
     *
     * @param t this is the t value of the parametric curve. t is clamped to be between 0 and 1 inclusive.
     * @return this returns the point requested.
     */
    @Override
    public Vector2D get(double t) {
        TValue.check(t);
        return getDerivative(0, t);
    }

    @Override
    public double closestParameter(Vector2D position, double initialGuess) {
        double[] searchEstimates = new double[] {0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, initialGuess};
        double closestDist = 1e9;
        double bestGuess = 0;

        for (double t : searchEstimates) {
            double dist = get(t).distanceSquared(position);

            if (dist < closestDist) {
                closestDist = dist;
                bestGuess = t;
            }
        }

        initialGuess = bestGuess;

        for (int i = 0; i < SEARCH_LIMIT; i++) {
            Vector2D lastPos = get(initialGuess);
            Vector2D firstDeriv = derivative(initialGuess);
            Vector2D secondDeriv = getDerivative(2, initialGuess);

            double deltaX = lastPos.x() - position.x();
            double deltaY = lastPos.y() - position.y();
            double firstDerivative = 2 * ((deltaX * firstDeriv.x()) + (deltaY * firstDeriv.y()));
            double secondDerivative = 2
                    * ((deltaX * secondDeriv.x())
                            + (deltaY * secondDeriv.y())
                            + (firstDeriv.x() * firstDeriv.x())
                            + (firstDeriv.y() * firstDeriv.y()));

            initialGuess = clamp(initialGuess - firstDerivative / (secondDerivative + 1e-9), 0, 1);
            if (get(initialGuess).distance(lastPos) < 0.1) break;
        }

        return initialGuess;
    }

    public Vector2D getDerivative(int n, double t) {
        Vector outVel = new Vector(
                this.tMatrix.getTMatrix(n, t).times(this.cachedMatrix).getRow(0));
        return Vector2D.cartesian(outVel.get(0), outVel.get(1));
    }

    /**
     * This returns the derivative on the BezierCurve that is specified by the parametric t value.
     * This is returned as a Vector2D, and this Vector2D is the tangent to the BezierCurve.
     *
     * @param t this is the t value of the parametric curve. t is clamped to be between 0 and 1 inclusive.
     * @return this returns the derivative requested.
     */
    public Vector2D derivative(double t) {
        TValue.check(t);
        return getDerivative(1, t);
    }

    /**
     * Returns the ArrayList of control points for this BezierCurve.
     *
     * @return This returns the control points.
     */
    public ArrayList<Vector2D> getControlPoints() {
        return controlPoints;
    }

    /**
     * Returns the approximate length of this BezierCurve.
     *
     * @return This returns the length.
     */
    public double length() {
        return length;
    }

    @Override
    public double remainingDistance(double t) {
        TValue.check(t);
        return (1 - pathCompletion(t)) * length;
    }

    @Override
    public double curvature(double t) {
        TValue.check(t);
        Vector2D derivative = derivative(t);
        Vector2D secondDerivative = getDerivative(2, t);
        double derivMag = derivative.magnitude();

        if (derivMag < 1e-9) return 0;
        return (derivative.det(secondDerivative)) / derivMag / derivMag / derivMag;
    }

    @Override
    public double pathCompletion(double t) {
        TValue.check(t);
        if (length == 0) return 0.0;
        return Utils.clamp(completionMap.interpolateKey(t) / length, 0, 1);
    }

    /**
     * Returns the t value corresponding to a given path completion percentage.
     * @param pathCompletion the path completion percentage; [0, 1]
     * @return returns the t value corresponding to the path completion percentage.
     */
    @Override
    public double parameter(double pathCompletion) {
        return completionMap.interpolateValue(pathCompletion * length);
    }

    /**
     * Generates a BezierCurve that passes through the given points
     * @param points vararg of points; requirements more than two points
     * @return the BezierCurve passing through the points
     */
    public static BezierCurve through(Pose... points) {
        return interpolateThroughPoints(points);
    }

    private static BezierCurve interpolateThroughPoints(Pose... points) {
        if (points.length < 3) {
            throw new IllegalArgumentException("Too few control points");
        }

        double[] tValues = Utils.linspace(0, 1, points.length);
        PolynomialMatrix polynomialMatrix = new PolynomialMatrix(points.length);

        Matrix bernstein = polynomialMatrix
                .getTMatrix(0, tValues)
                .times(BasisMatrixSupplier.getBezierCharacteristicMatrix(points.length));

        double[][] targets = new double[points.length][2];
        for (int i = 0; i < points.length; i++) {
            targets[i][0] = points[i].x();
            targets[i][1] = points[i].y();
        }

        Matrix result = bernstein.invert().times(new Matrix(targets));

        List<Vector2D> controlPoints = new ArrayList<>();

        for (int i = 0; i < points.length; i++) {
            controlPoints.add(Vector2D.cartesian(result.get(i, 0), result.get(i, 1)));
        }

        return new BezierCurve(controlPoints);
    }
}
