[versions]
ftc = "11.2.0"
dokka = "2.2.0"
agp = "8.7.3"
kotlin = "2.3.21"
deployer = "0.18.0"
spotless = "8.4.0"

[libraries]
ftc-robot-core = { group = "org.firstinspires.ftc", name = "RobotCore", version.ref = "ftc" }
ftc-hardware = { group = "org.firstinspires.ftc", name = "Hardware", version.ref = "ftc" }
dokka-java-plugin = { group = "org.jetbrains.dokka", name = "kotlin-as-java-plugin", version.ref = "dokka" }

[bundles]
ftc = ["ftc-robot-core", "ftc-hardware"]

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
deployer = { id = "io.deepmedia.tools.deployer", version.ref = "deployer" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
