// Generated by tools/generate-config.js; edit config/robot.json.
#pragma once
namespace robot_config {
inline constexpr int frontLeft=-11;
inline constexpr int backLeft=-20;
inline constexpr int frontRight=1;
inline constexpr int backRight=10;
inline constexpr float cartridgeRpm=200.00000000f;
inline constexpr float wheelDiameterIn=3.25000000f;
inline constexpr float widthIn=10.50000000f;
inline constexpr float wheelbaseIn=10.50000000f;
inline constexpr float externalGearRatio=1.00000000f;
inline constexpr float linear_kP=9.50000000f;
inline constexpr float linear_kI=0.02000000f;
inline constexpr float linear_kD=2.50000000f;
inline constexpr float linear_kV=0.42000000f;
inline constexpr float angular_kP=3.40000000f;
inline constexpr float angular_kI=0.05000000f;
inline constexpr float angular_kD=2.00000000f;
inline constexpr float angular_kV=0.18000000f;
}
